version: "3.8"

services:
  global_button:
    image: oven/bun:alpine
    working_dir: /app
    volumes:
      - /home/user/selfhosted/global_button:/app
    command: bun index.ts
    ports:
      - "3001:3000"
  main:
    image: oven/bun:alpine
    working_dir: /app
    volumes:
      - /home/user/selfhosted/main:/app
    command: bun index.ts
    ports:
      - "3002:3000"
  nginx:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - main
      - global_button
